Game v2.0
infoshareacademy/jfdd13-dreamteam pull request #33
Opened 2020-01-07 23:08 UTC by Rednaxela700

I want to rewrite whole game in OOP style. Feel free to comment and check my code.
Old game files are located in game/js/game dir. New files are in game/js/game2/.

Main goals:
-  clean  code
- modules
- DRY

2020-01-09 00:31 UTC, Rednaxela700 commented
Milestone: player object can be rendered on the board and controlled with arrow keys!
Test it by:
- opening root/game/game2.html
- enter console
- game.create('player')
- game.render(game.board.children[0])

2020-01-11 00:39 UTC, Rednaxela700 commented
Update:
- board btns have been put into Board obj, but left uncontrolled for now
- created some intervals, birds fly into the left, clearing them on hit
- collisions are being detected on exactly same position of player and another element on x-axis
- destroy freezes an object instead of deleting anything

2020-01-12 22:56 UTC, Rednaxela700 commented
🚀 Another update:
- collisions are now being detected basing on circle radius (quite effective, check it out!)
- added basic support for game buttons (adding listeners on obj load, removing listeners on btn click) 🏷  todo: no action for help and back buttons

2020-01-12 23:47 UTC, cytrowski commented on game/js/game2/game.js
> +    Object.freeze(el);
Why do you need Object.freeze?

2020-01-12 23:50 UTC, cytrowski commented on game/js/game2/game.js
> -        const randPositions = [0, 50, 150, 200, 250, 280, 350, 400];
I see that you changed the positions but based on the commit message I have no idea why you did that :) Explain please ;)

2020-01-12 23:52 UTC, cytrowski commented on game/js/game2/game.js
> +      hideBtns()
You do hideBtns and then removeEventListeners in a sequence in multiple places - consider making a function for that and call it instead, eg. `function cleanup() { hideBtns(); removeEventListeners() }`

2020-01-12 23:55 UTC, cytrowski commented on game/js/game2/game.js
> +  }
There is something wrong with indentation for sure

2020-01-12 23:57 UTC, cytrowski commented on game/js/game2/game.js
> +  activeIntervals = [];
Where is the activeIntervals variable declaration?

2020-01-12 23:57 UTC, Rednaxela700 commented on game/js/game2/game.js
> -        const randPositions = [0, 50, 150, 200, 250, 280, 350, 400];
1) I've just added preetierrc file to the project. 
2) I was struggling for some time with those positions, at first I didn't realise how axis are being calculated. I hope I finally fixed it in dffb3fa

2020-01-12 23:59 UTC, cytrowski commented on game/js/game2/game.js
> +    clearIntervals(this.activeIntervals);
Where is the definition of `clearIntervals`?

2020-01-12 23:59 UTC, Rednaxela700 commented on game/js/game2/game.js
> +    Object.freeze(el);
I wanted to keep my objects still outside the game board and save the array they're being pushed to "untouched"

2020-01-13 00:00 UTC, cytrowski commented on game/js/game2/game.js
> +      this.board.children.filter(el => el.type === "player")[0].keySupport
If you are interested only in the first element with type "player" then use `find` instead of `filter`. It stops iteration immediately. Filter iterates over every element in an array even if it finds one already.

2020-01-13 00:02 UTC, cytrowski commented on game/js/game2/game.js
> +        this.handleCollision();
Why this one needs to be inside an interval?

2020-01-13 00:04 UTC, cytrowski commented on game/js/game2/game.js
> +      this.gameIntervals.push(creation, elementsMove, collision, destroy);
This looks like you are creating a lot of intervals here. Are they really needed? I cannot figure out their use cases based on the names.

2020-01-13 00:05 UTC, cytrowski commented on game/js/game2/game.js
> +      Object.freeze(el);
Whey we need to Object.freeze it?

2020-01-13 00:09 UTC, cytrowski commented on game/js/game2/game.js
> +    for(let i = 1; i < boardElements.length; i++) {
Why did you replace forEach with for loop?

2020-01-13 00:10 UTC, cytrowski commented on game/js/game2/game.js
> -        const randPositions = [0, 50, 150, 200, 250, 280, 350, 600];
What was broken here?

2020-01-13 00:11 UTC, cytrowski commented on game/js/game2/game.js
> +      arr.hasOwnProperty("length")
Did you check `Array.isArray` method? :)

2020-01-13 00:13 UTC, cytrowski commented on game/js/game2/game.js
> +    if (typeof direction === "string" && this.destroyed === false) {
You can reduce indentation in this whole method if you use early return pattern.

```js
if (typeof direction !== "string" || this.destroyed === true) {
  return;
}
```

2020-01-13 00:14 UTC, cytrowski commented on game/js/game2/game.js
> +        this.position.y <= 599 - this.size.h ? this.move("down") : null;
Oh noes. Never do it that way. Ternary operator is reserved for calculating values conditionally in expressions. In this case you should use `if`

2020-01-13 00:16 UTC, Rednaxela700 commented on game/js/game2/game.js
> +    for(let i = 1; i < boardElements.length; i++) {
just to make sure I know what I'm doing, one forEach after another felt... boring :)

2020-01-13 00:17 UTC, cytrowski commented on game/js/game2/game.js
> +        this.position.x >= 1 ? this.move("left") : null;
Can't you validate `this.position.x` within the `move` method? This code looked better previously. And also - do not use ternary operator as an `if` statement shorthand

2020-01-13 00:19 UTC, cytrowski commented on game/js/game2/game.js
> +          this.changePosition();
You can just call `this.changePosition()` once after the switch statement. No need to repeat it in every case

2020-01-13 00:19 UTC, cytrowski commented on game/js/game2/game.js
> +    console.log(el.id)
// TODO implement ;)

2020-01-13 00:19 UTC, Rednaxela700 commented on game/js/game2/game.js
> +      arr.hasOwnProperty("length")
I did, as far as I recall this method doesn't work on NodeLists which I have in another method, so I figured out it could be good idea to check if my "processing data" is iterable.
In this case I'll change it to .isArray of course!

2020-01-13 00:23 UTC, cytrowski commented on game/js/game2/game.js
> +    }
```js
const assets = {
  birdz: 'bird_eagle',
  bird: 'bird_gull',
  tree: 'tree3',
  player: 'player_plane'
}

child.style.backgroundImage = `url('img/${assets[el.name.toLowerCase()]}.png')`;

```

2020-01-13 00:24 UTC, Rednaxela700 commented on game/js/game2/game.js
> +          this.changePosition();
"In case of unforseeen arguments" I thought it would be better to put it into case statements,
otherwise I call this.changePosition on default which is null. Can it have negative impact on my code?

2020-01-13 00:27 UTC, Rednaxela700 commented on game/js/game2/game.js
> +    }
wow! Never seen, TBD.

2020-01-13 00:30 UTC, cytrowski commented on game/js/game2/game.js
> +          this.changePosition();
As far as I see it should be fine. `changePosition` only changes some css to a value that is controlled by the "good" cases above. It will be fine ;)

2020-01-13 00:30 UTC, cytrowski commented on game/js/game2/game.js
> +    }
That's my little trickery ;)

2020-01-13 00:31 UTC, Rednaxela700 commented on game/js/game2/game.js
> +        this.position.x >= 1 ? this.move("left") : null;
I'll put if statements then, I could but I keep move method in another class (it was my attemp on composition over inheritance)

2020-01-13 00:31 UTC, cytrowski commented on game/js/game2/game.js
> +    }
I used that to abuse Redux boilerplate a bit: https://github.com/cytrowski/til/blob/master/tech3camp/2019-01/examples.md

2020-01-13 00:32 UTC, Rednaxela700 commented on game/js/game2/game.js
> +        this.position.y <= 599 - this.size.h ? this.move("down") : null;
TBD.

2020-01-13 00:47 UTC, cytrowski commented on game/js/game2/game.js
> +        this.position.x >= 1 ? this.move("left") : null;
Well, in that case try building the move method in a way that it is composable:
```js
  move(direction, validate) {
    if (validate(this.position.x) === false) {
      return;
    }
    // the rest of the movement logic here
  }
```

and then call it like that:
```js
this.move('left', x => x >= 1)
```

2020-01-13 00:49 UTC, cytrowski commented on game/js/game2/game.js
> +        this.position.y <= 599 - this.size.h ? this.move("down") : null;
Check this one: https://github.com/infoshareacademy/jfdd13-dreamteam/pull/33#discussion_r365625019

2020-01-13 01:07 UTC, Rednaxela700 commented on game/js/game2/game.js
> +    clearIntervals(this.activeIntervals);
put it up into constructor func

2020-01-13 01:09 UTC, Rednaxela700 commented on game/js/game2/game.js
> +      this.board.children.filter(el => el.type === "player")[0].keySupport
done.

2020-01-13 01:35 UTC, Rednaxela700 commented on game/js/game2/game.js
> +    if (typeof direction === "string" && this.destroyed === false) {
done. Consider to start counting for each time you say reduce  :D

2020-01-13 01:51 UTC, Rednaxela700 commented on game/js/game2/game.js
> +    }
A man who reduced a tool designed to reduce... Beautiful, but merciless ;)

2020-01-13 12:34 UTC, michal-kusnierz commented on game/js/game2/game.js
> +    }
> wow! Never seen, TBD.

Me neither, thnx @cytrowski :1st_place_medal:

2020-01-13 13:32 UTC, cytrowski commented
> default for Tabs is 'false' - do we need 'use-tabs: false' in prettierrc?

No, you do not :)

2020-01-13 18:56 UTC, Rednaxela700 commented on game/js/game2/game.js
> -        const randPositions = [0, 50, 150, 200, 250, 280, 350, 400];
> > default for Tabs is 'false' - do we need 'use-tabs: false' in prettierrc?
> 
> No, you do not :)

fixed 👍

2020-01-13 20:15 UTC, Rednaxela700 commented on game/js/game2/game.js
> +      Object.freeze(el);
I change elements position on the board using intervals. I wanted to stop them when they get  off the board. If there's a better way to hold elements still as they go away please let me know!

2020-01-13 20:53 UTC, Rednaxela700 commented on game/js/game2/game.js
> +        this.position.x >= 1 ? this.move("left") : null;
I use the same method to move the player and a set of other objects. In fact only player cannot step out of the board. So I'd have to add it to validation and check all objects (elements on board) in the array... It already feels "not the best solution"

2020-01-13 21:14 UTC, Rednaxela700 commented on game/js/game2/game.js
> +      this.gameIntervals.push(creation, elementsMove, collision, destroy);
hope it got better in 34ef66d

2020-01-15 00:05 UTC, Rednaxela700 commented on game/js/game2/game.js
> +      arr.hasOwnProperty("length")
I decided to use Object.is as a check for iterable data (aka NodeLists)

2020-01-15 09:38 UTC, cytrowski commented on game/js/game2/game.js
> +                    }, i + "1000")
Why `"1000"` not `1000` - `setTimeout` accepts a number as the timeout duration in ms

2020-01-15 09:39 UTC, cytrowski commented on game/js/game2/game.js
> +            }, increaseDifficulty())
`increaseDifficulty` does not return any reasonable number that can be used here. It looks weird. What's the expected outcome?

2020-01-15 18:18 UTC, Rednaxela700 commented on game/js/game2/game.js
> +                    }, i + "1000")
It was very late at night. I forgot about existence of multiplication.

2020-01-15 18:20 UTC, Rednaxela700 commented on game/js/game2/game.js
> +            }, increaseDifficulty())
I expected a number which will be a setTimeout() parameter. I want to iterate backwards on the array I set inside increaseDifficulty() - aka refreshRates[]

2020-01-17 19:07 UTC, Rednaxela700 commented
I had some trouble with return values from switch. Current solution is readable and solves the problem :) btw, I don't see the reason to add else statement as in above statements I compare only numbers covering probably all possible cases and there's no type coercion. I think it's fine. If you know any edge cases please let me know!

2020-11-04 08:38 UTC, miklosz requested changes
Udefined SASS variables causing compiler failure. Add missing varaibles

2020-11-16 15:07 UTC, Rednaxela700 commented
TY @miklosz, resolved.

2020-11-16 15:08 UTC, merged